
plugins {
    id 'ca.coglinc.javacc' version '2.4.0'
    id 'antlr'
    id 'application'
}

description "CATs"
configurations { antlr4 }
dependencies {

    implementation project(":key.core")

    implementation project(":key.ui")
    implementation project(":key.core.rifl")

    implementation project(":key.core.proof_references")
    implementation project(":key.core.symbolic_execution")
    implementation project(":key.removegenerics")

    implementation group: 'net.java.dev.javacc', name: 'javacc', version: '4.0'
    implementation group: 'org.antlr', name: 'antlr-runtime', version: '3.5.3'
    implementation group: 'antlr', name: 'antlr', version: '2.7.7'

    javacc group: 'net.java.dev.javacc', name: 'javacc', version: '4.0'
    antlr group: 'org.antlr', name: 'antlr', version: '3.5.3'   // use ANTLR version 3

    antlr4 "org.antlr:antlr4:4.13.1"
    api "org.antlr:antlr4-runtime:4.13.1"
    //implementation group: 'com.google.guava', name: 'guava', version: '28.1-jre'
}
application {
    // Define the main class for the application.
    mainClass = 'key4cats.KeY4CATs'
}

tasks.register('copyRules', Copy) {
    from "../key.ui/examples/traces/"
    into "src/test/resources/"
    include("tracerules.key")
    include("TestsCATs.java")
}


tasks.processTestResources.dependsOn(copyRules)
