import java.text.SimpleDateFormat

plugins {
    id 'ca.coglinc.javacc' version '2.4.0'
    id 'antlr'
    id 'application'
    id "com.gradleup.shadow" version "8.3.5"
}

description "CATs"
version = ""
configurations { antlr4 }
dependencies {
    implementation 'com.github.javaparser:javaparser-core:3.26.3'
    implementation("ch.qos.logback:logback-classic:1.4.14")
    implementation project(":key.core")

    implementation project(":key.ui")
    implementation project(":key.core.rifl")

    implementation project(":key.core.proof_references")
    implementation project(":key.core.symbolic_execution")
    implementation project(":key.removegenerics")

    implementation 'commons-cli:commons-cli:1.9.0'

    implementation group: 'net.java.dev.javacc', name: 'javacc', version: '4.0'
    implementation group: 'org.antlr', name: 'antlr-runtime', version: '3.5.3'
    implementation group: 'antlr', name: 'antlr', version: '2.7.7'

    javacc group: 'net.java.dev.javacc', name: 'javacc', version: '4.0'
    antlr group: 'org.antlr', name: 'antlr', version: '3.5.3'   // use ANTLR version 3

    antlr4 "org.antlr:antlr4:4.13.1"
    api "org.antlr:antlr4-runtime:4.13.1"
    //implementation group: 'com.google.guava', name: 'guava', version: '28.1-jre'
}
application {
    // Define the main class for the application.
    mainClass = 'key4cats.KeY4CATs'
}

shadowJar {
    archiveClassifier.set("")
    archiveBaseName.set("KeY4CATs")
}



tasks.register('copyRules', Copy) {
    from "../key.ui/examples/traces/"
    into "src/test/resources/"
//    include("tracerules.key")
    include("TestsCATs.java")
}
tasks.register('saveResults'){
    String name = """results/results_${new SimpleDateFormat("yyMMdd_HHmm").format(new Date())}.csv"""
    new File(projectDir, "results_info").text = "$name"
}


tasks.copyRules.dependsOn(saveResults)
tasks.processTestResources.dependsOn(copyRules)
