#!/bin/bash

echo "load the generated proof obligation for oneRoundCAT"
echo "(make sure you run \"oneRoundCATOnlyProof\" before)"
echo "if correctly loaded, the proof should succeed"
set +x
key4cats -po ../../resources/oneRoundCAT.key
set -x